baseURL = "http://test.staleyland.com/"
languageCode = "en-us"
title = "Staleyland.com"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = "UA-40493136-2"
enableRobotsTXT = true

[params]
    author = "Sean Staley"
    description = "Personal website for Sean Staley"
    instagram = "https://instagram.com/staleyman23"
    github = "https://github.com/seanstaley/"
    twitter = "https://twitter.com/staleyman23"
    linkedin = "https://www.linkedin.com/in/seanstaley/"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Quicksand" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    background_color_class = "bg-black"
    highlightLanguages = ["java", "python", "bash", "Dockerfile", "json"]
    featured_image = '/images/IMG_5964.jpeg'
    recent_posts_number = 2
