baseURL = "http://www.staleyland.com/"
languageCode = "en-us"
title = "Staleyland.com"
theme = "minimal"

[params]
    author = "Sean Staley"
    description = "Personal website for Sean Staley"
    githubUsername = "seanstaley"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Quicksand" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["java", "python", "bash", "Dockerfile", "json"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

#[[menu.main]]
#    url = "/post/"
#    name = "Posts"
#    weight = 2

[[menu.main]]
    url = "/app/"
    name = "Apps"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:sean@staleyland.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/seanstaley/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://instagram.com/staleyman23"
    name = "instagram"
    weight = 3

[[menu.icon]]
    url = "https://twitter.com/staleyman23/"
    name = "twitter"
    weight = 4

[[menu.icon]]
    url = "https://www.linkedin.com/in/seanstaley/"
    name = "linkedin"
    weight = 5
